name: deploy-auth

on:
  push: # close / merge a RP
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build: # job id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout all code inside of our repo
      - run: cd auth && docker build -t catalinleca95/auth . # build the image and push it to dockerhub
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: # need to add the env vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push catalinleca95/auth
